name: "ci"
on:
  push:
    branches: ["main"]
  pull_request:

defaults:
  run:
    working-directory: ./packages/maplibre-react-components

jobs:
  lint:
    name: Eslint and Tsc
    strategy:
      fail-fast: true
      matrix:
        node-versions: [ '20' ]

    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-versions }}
          cache: 'pnpm'

      - name: "Install JS dependencies"
        run: "pnpm i --frozen-lockfile"

      - name: "Eslint"
        run: "pnpm run lint:check"

      - name: "Tsc"
        run: "pnpm run tsc:check"

      - name: "Test"
        run: "pnpm run test-run"
